const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',



    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    USER_CLIENT_LOGIN_SUCCESS: 'USER_CLIENT_LOGIN_SUCCESS',
    ADD_CLIENT_SUCCESS: 'ADD_CLIENT_SUCCESS',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILDED: 'FETCH_GENDER_FAILDED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILDED: 'FETCH_ROLE_FAILDED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILDED: 'FETCH_ALL_USERS_FAILDED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILDED: 'CREATE_USER_FAILDED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILDED: 'EDIT_USER_FAILDED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILDED: 'DELETE_USER_FAILDED',

    CREATE_CLIENT_SUCCESS: 'CREATE_CLIENT_SUCCESS',
    CREATE_CLIENT_FAILDED: 'CREATE_CLIENT_FAILDED',

    //COURSE

    FETCH_ALL_COURSES_SUCCESS: 'FETCH_ALL_COURSES_SUCCESS',
    FETCH_ALL_COURSES_FAILDED: 'FETCH_ALL_COURSES_FAILDED',

    CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
    CREATE_COURSE_FAILDED: 'CREATE_COURSE_FAILDED',

    EDIT_COURSE_SUCCESS: 'EDIT_COURSE_SUCCESS',
    EDIT_COURSE_FAILDED: 'EDIT_COURSE_FAILDED',

    DELETE_COURSE_SUCCESS: 'DELETE_COURSE_SUCCESS',
    DELETE_COURSE_FAILDED: 'DELETE_COURSE_FAILDED',

    FETCH_TOP_COURSES_SUCCESS: 'FETCH_TOP_COURSES_SUCCESS',
    FETCH_TOP_COURSES_FAILDED: 'FETCH_TOP_COURSES_FAILDED',

    SAVE_DETAIL_COURSE_SUCCESS: 'SAVE_DETAIL_COURSE_SUCCESS',
    SAVE_DETAIL_COURSE_FAILDED: 'SAVE_DETAIL_COURSE_FAILDED',

    SAVE_CREATE_BLOG_SUCCESS: 'SAVE_CREATE_BLOG_SUCCESS',
    SAVE_CREATE_BLOG_FAILDED: 'SAVE_CREATE_BLOG_FAILDED',

    //BLOGS
    FETCH_ALL_BLOGS_SUCCESS: 'FETCH_ALL_BLOGS_SUCCESS',
    FETCH_ALL_BLOGS_FAILDED: 'FETCH_ALL_BLOGS_FAILDED',

    FETCH_ALL_BLOGS_USER_SUCCESS: 'FETCH_ALL_BLOGS_USER_SUCCESS',
    FETCH_ALL_BLOGS_USER_FAILDED: 'FETCH_ALL_BLOGS_USER_FAILDED',

    DELETE_BLOG_SUCCESS: 'DELETE_BLOG_SUCCESS',
    DELETE_BLOG_FAILDED: 'DELETE_BLOG_FAILDED',

    EDIT_BLOG_SUCCESS: 'EDIT_BLOG_SUCCESS',
    EDIT_BLOG_FAILDED: 'EDIT_BLOG_FAILDED',

    FETCH_TOP_BLOGS_SUCCESS: 'FETCH_TOP_BLOGS_SUCCESS',
    FETCH_TOP_BLOGS_FAILDED: 'FETCH_TOP_BLOGS_FAILDED',

    //VIDEO
    FETCH_ALL_VIDEOS_SUCCESS: 'FETCH_ALL_VIDEOS_SUCCESS',
    FETCH_ALL_VIDEOS_FAILDED: 'FETCH_ALL_VIDEOS_FAILDED',

    FETCH_ALL_VIDEOS_COURSE_SUCCESS: 'FETCH_ALL_VIDEOS_COURSE_SUCCESS',
    FETCH_ALL_VIDEOS_COURSE_FAILDED: 'FETCH_ALL_VIDEOS_COURSE_FAILDED',

    CREATE_VIDEO_SUCCESS: 'CREATE_VIDEO_SUCCESS',
    CREATE_VIDEO_FAILDED: 'CREATE_VIDEO_FAILDED',

    EDIT_VIDEO_SUCCESS: 'EDIT_VIDEO_SUCCESS',
    EDIT_VIDEO_FAILDED: 'EDIT_VIDEO_FAILDED',

    DELETE_VIDEO_SUCCESS: 'DELETE_VIDEO_SUCCESS',
    DELETE_VIDEO_FAILDED: 'DELETE_VIDEO_FAILDED',

    //ROADMAP
    FETCH_ALL_ROADMAPS_SUCCESS: 'FETCH_ALL_ROADMAPS_SUCCESS',
    FETCH_ALL_ROADMAPS_FAILDED: 'FETCH_ALL_ROADMAPS_FAILDED',

    CREATE_ROADMAP_SUCCESS: 'CREATE_ROADMAP_SUCCESS',
    CREATE_ROADMAP_FAILDED: 'CREATE_ROADMAP_FAILDED',

    EDIT_ROADMAP_SUCCESS: 'EDIT_ROADMAP_SUCCESS',
    EDIT_ROADMAP_FAILDED: 'EDIT_ROADMAP_FAILDED',

    DELETE_ROADMAP_SUCCESS: 'DELETE_ROADMAP_SUCCESS',
    DELETE_ROADMAP_FAILDED: 'DELETE_ROADMAP_FAILDED',

    //SCHOLASTIC
    FETCH_ALL_SCHOLASTICS_SUCCESS: 'FETCH_ALL_SCHOLASTICS_SUCCESS',
    FETCH_ALL_SCHOLASTICS_FAILDED: 'FETCH_ALL_SCHOLASTICS_FAILDED',

    CREATE_SCHOLASTIC_SUCCESS: 'CREATE_SCHOLASTIC_SUCCESS',
    CREATE_SCHOLASTIC_FAILDED: 'CREATE_SCHOLASTIC_FAILDED',

    EDIT_SCHOLASTIC_SUCCESS: 'EDIT_SCHOLASTIC_SUCCESS',
    EDIT_SCHOLASTIC_FAILDED: 'EDIT_SCHOLASTIC_FAILDED',

    DELETE_SCHOLASTIC_SUCCESS: 'DELETE_SCHOLASTIC_SUCCESS',
    DELETE_SCHOLASTIC_FAILDED: 'DELETE_SCHOLASTIC_FAILDED',
})

export default actionTypes;